#!/bin/bash

# This program helps use solid to create and manage new projects

# Think of it as a config tool, a little like rails for ruby on rails

command=$1
directory=$2
option=$3

output="source"

if [ $command ]
        then
                echo "Processing command $command"
        else
                echo "Usage: solid command project"
                echo "Commands:"
                echo "create (creates a directory in working directory with name of project and application template)"
                echo "module (creates a module for current project or solid with the name of module project and module template)"
                echo "example: solid create cargame"
                exit
fi

if [ $SOLIDCORE ]
        then
                echo "active solid dir: $SOLIDCORE"
        else
                echo "solid has not been installed properly"
                echo "Please set variable SOLIDCORE by adding the line "export SOLIDCORE=/path/to/solid" to ~/.bashrc"
                exit
fi 

if [ -d $directory ]
        then
                echo "$directory already exists! Quitting."
                exit
        else
                if [ -d ../$directory ]
                    then
                            echo "Currently in $directory. Quitting."
                            exit
                fi

                if [ $PWD == $SOLIDCORE ]
                    then
                            echo "Currently in $SOLIDCORE. Creating module for solid."
#                            $directory = $SOLIDCORE/source/modules/$directory

                            exit
                fi

                if [ $command == "create" ]
                    then
                        echo "Creating project $directory"
                        mkdir $directory
                        echo "Copying files ..."
                        cp -rf $SOLIDCORE/examples/templates/application/* $directory
                        cp -rf $SOLIDCORE/standarddata/data $directory
                        sed "s|SOLIDCORE =.*|SOLIDCORE=$SOLIDCORE|g" $SOLIDCORE/examples/templates/application/Makefile > $directory/Makefile
                fi
                if [ $command == "module" ]
                    then
                        echo "Creating module $directory"
                        mkdir $directory
                        echo "Copying files ..."
                        cp -rf $SOLIDCORE/examples/templates/module/* $directory
                        sed "s|SOLIDCORE =.*|SOLIDCORE=$SOLIDCORE|g" $SOLIDCORE/examples/templates/application/Makefile > $directory/Makefile
                fi
                if [ $command == "new" ]
                    then
                        if [ $directory == "scene" ]
                            then
                                sed "s|Scene|$option|" $SOLIDCORE/source/tools/templates/scene.h > $output/$option.h
                                sed "s|Scene|$option|g" $SOLIDCORE/source/tools/templates/scene.cpp > $output/$option.cpp
                        fi
                fi
                echo "Done"
fi

